
version: 2

updates: 

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "eto.forms"
      - dependency-name: "skiasharp"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
