
name: build

on:
  push:
    tags: ['v*']
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # manual trigger

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: |
        dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained Eto.RainbowLoading.Demo
        # include native libSkiaSharp when publishing selfcontained 
        dotnet publish -r linux-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained Eto.RainbowLoading.Demo
        # wrap artifacts in tar archives to maintain permissions intact
        tar --directory=Eto.RainbowLoading.Demo/bin/Mac64/Debug/net6.0/osx-x64/publish -cvf Eto.RainbowLoading.Demo.Mac.tar Eto.RainbowLoading.Demo.app
        tar --directory=Eto.RainbowLoading.Demo/bin/Gtk/Debug/net6.0/linux-x64/publish -cvf Eto.RainbowLoading.Demo.Gtk.tar Eto.RainbowLoading.Demo

    - name: Upload Eto.RainbowLoading.Mac artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Eto.RainbowLoading.Demo.Mac
        path: Eto.RainbowLoading.Demo.Mac.tar

    - name: Upload Eto.RainbowLoading.Gtk artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Eto.RainbowLoading.Demo.Gtk
        path: Eto.RainbowLoading.Demo.Gtk.tar

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: |
        dotnet build -c Release Eto.RainbowLoading
        dotnet build -c Release Eto.RainbowLoading.Skia
        dotnet publish -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained Eto.RainbowLoading.Demo
    
    - name: Upload Eto.RainbowLoading.Wpf artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Eto.RainbowLoading.Demo.Wpf
        path: Eto.RainbowLoading.Demo/bin/Wpf/Debug/net6.0-windows/win-x64/publish/Eto.RainbowLoading.Demo.exe

    - name: Upload nuget artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: ./**/bin/Release/*.nupkg

    - name: Push to nuget.org
      if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
      run: |
         dotnet nuget push '.\Eto.RainbowLoading\bin\Release\*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
         dotnet nuget push '.\Eto.RainbowLoading.Skia\bin\Release\*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
